services:
  - type: web
    name: tengapesa
    env: node
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8080
