
services:
  - type: web
    name: tengapesa
    env: node
    buildCommand: |
      rm -rf node_modules package-lock.json
      npm install --no-optional
      node fix-rollup.cjs
      mkdir -p node_modules/@rollup
      ln -sf "$(pwd)/node_modules/rollup" "$(pwd)/node_modules/@rollup/rollup-linux-x64-gnu" || true
      npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
    healthCheckPath: /healthz
    autoDeploy: true
    # Keep the service alive with regular health checks
    healthCheckGracePeriod: 300s
    # Enable keep-alive mechanism
    healthCheckTimeout: 30s
