services:
  - type: web
    name: tengapesa
    env: node    buildCommand: npm ci && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8080
