
services:
  - type: web
    name: tengapesa
    env: node
    buildCommand: |
      npm ci
      node fix-dependencies.js
      npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true
