
services:
  - type: web
    name: tengapesa
    env: node    buildCommand: |
      rm -rf node_modules package-lock.json
      npm install --no-optional
      node fix-rollup.js
      npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true
